---
services:
  - docker

install:
  - docker build -t ansible-roles-trusty-test tests/support
  - docker run --rm -it --privileged -v $PWD:/etc/ansible/roles/openvpn:ro ansible-roles-trusty-test

before_script:
  - docker images

script:
  - docker ps -a
