---
- name: Add OpenVPN repo GPG key
  apt_key:
    id: E158C569
    url: https://swupdate.openvpn.net/repos/repo-public.gpg
  when: openvpn_use_external_repo

- name: Add OpenVPN repo sources
  apt_repository:
    filename: openvpn
    repo: "deb http://swupdate.openvpn.net/apt {{ ansible_lsb.codename }} main"
  when: openvpn_use_external_repo

- name: Install requirements
  apt:
    name: "{{ item }}"
    state: present
  with_items: [openvpn, udev, openssl, zip]
  register: _openvpn_reqs_install

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  when: openvpn_use_pam_users|default(false)
  with_items: [libpam-pwdfile, python-passlib]

- name: Install easy-rsa package
  apt:
    name: easy-rsa
    state: present
  when: openvpn_use_system_easyrsa

- name: Install LDAP dependencies
  apt:
    name: openvpn-auth-ldap
    state: present
  when: openvpn_use_ldap

- name: Install bridge dependencies
  apt:
    name: bridge-utils
    state: present
  when: openvpn_bridge
